stages:
  - source
  - build
  - deploy

getSource:
  stage: source
  script:
    - devbox run get-source

buildFrontend:
  stage: build
  needs: ["getSource"]
  script:
    - devbox run build-frontend

deploy:
  stage: deploy
  needs: ["buildFrontend"]
  script:
    - sudo -u boilerplate devbox run deploy
