stages:
  - source
  - build
  - deploy

getSource:
  stage: source
  script:
    - devbox run get-source

buildFrontend:
  stage: build
  needs: ["getSource"]
  script:
    - devbox run build-frontend

buildCMS:
  stage: build
  needs: ["getSource"]
  script:
    - devbox run build-cms

deploy:
  stage: deploy
  needs: ["buildFrontend", "buildCMS"]
  variables:
    USER: "boilerplate"
  script:
    - sudo -u ${USER} bash -c "cd /home/${USER}/public_html; devbox run deploy"
