version: "3"

dotenv:
  - .env.local # Highest priority - local developer overrides
  - .env.{{.ENV}} # Environment-specific settings

vars:
  # GitLab CI predefined variables will be available in the environment
  BUILD_PATH: '{{.BUILD_PATH | default "/home/gitlab-runner/private"}}'
  CI_COMMIT_BRANCH: "{{.CI_COMMIT_BRANCH}}"
  CI_REPOSITORY_URL: "{{.CI_REPOSITORY_URL}}"
  DEPLOY_PATH: '{{.DEPLOY_PATH | default "/home/boilerplate/public_html"}}'
  OWNER: '{{.OWNER | default "boilerplate"}}'

tasks:
  get-source:
    desc: "Clones the repository into the build path."
    dir: "{{.BUILD_PATH}}"
    cmds:
      - echo "Cleaning old build..."
      - sudo rm -rf *
      - echo "Getting source..."
      - git clone {{.CI_REPOSITORY_URL}} source
      - cd source && git checkout {{.CI_COMMIT_BRANCH}}

  build-frontend:
    desc: "Builds the frontend application."
    dir: "{{.BUILD_PATH}}/source"
    cmds:
      - set -e
      - cd {{.BUILD_PATH}}/source
      - npm install
      - NODE_ENV=production npm run build
      - echo "Cleaning old build artifacts..."
      - sudo rm -rf {{.DEPLOY_PATH}}/.next
      - echo "Copying files to {{.DEPLOY_PATH}}"
      - sudo rsync -a --delete --exclude-from="rsync-exclude.txt" {{.BUILD_PATH}}/source/ {{.DEPLOY_PATH}}/
      - sudo chown {{.OWNER}}:{{.OWNER}} -R {{.DEPLOY_PATH}}

  build-cms:
    desc: "Builds the Strapi CMS."
    dir: "{{.BUILD_PATH}}/source/cms"
    cmds:
      - set -e
      - |
        if [ -d "{{.DEPLOY_PATH}}/cms/.strapi" ]; then
          echo "Strapi exists, skipping build..."
        else
          echo "Strapi does not exist, building..."
          npm install
          NODE_ENV=production npm run build
        fi
      - |
        if [ -d "{{.DEPLOY_PATH}}/cms/.strapi" ]; then
          echo "Strapi exists, skipping sync..."
        else
          echo "Strapi does not exist, syncing..."
          sudo rsync -a --delete --exclude-from="../rsync-exclude.txt" {{.BUILD_PATH}}/source/cms/ {{.DEPLOY_PATH}}/cms/
        fi
      - sudo chown {{.OWNER}}:{{.OWNER}} -R {{.DEPLOY_PATH}}

  deploy-frontend:
    desc: "Deploy the frontend"
    dir: "{{.DEPLOY_PATH}}"
    cmds:
      - pm2 delete frontend || true
      - unset name; pm2 start npm --name frontend -- run start -- --hostname 127.0.0.1
      - pm2 save

  deploy-cms:
    desc: "Deploy the CMS"
    dir: "{{.DEPLOY_PATH}}/cms"
    cmds:
      - pm2 delete cms || true
      - unset name; NODE_ENV=production pm2 start npm --name cms -- run start
      - pm2 save

  deploy:
    desc: "Deploying the application."
    dir: "{{.DEPLOY_PATH}}"
    deps: [deploy-frontend, deploy-cms]

  start:
    desc: "Starting the application."
    dir: "{{.DEPLOY_PATH}}"
    cmds:
      - unset name; PORT={{.APP_PORT}} pm2 start npm --name frontend -- run start -- --hostname 127.0.0.1
      - cd cms
      - pm2 delete cms || true
      - PORT={{.$CMS_PORT}} NODE_ENV=production pm2 start npm --name cms -- run start -- --hostname 127.0.0.1

  stop:
    desc: "Stopping the application."
    dir: "{{.DEPLOY_PATH}}"
    cmds:
      - pm2 delete frontend || true
